version: "3"
services:
  photos.z720.net:
    container_name: ${DOMAIN}
    environment:
      - LETSENCRYPT_EMAIL=letsencrypt@z720.net
      - LETSENCRYPT_HOST=photos.z720.net
      - VIRTUAL_HOST=photos.z720.net
    labels:
    - traefik.enable=true
    - traefik.http.routers.photos_z720_net.rule=Host(`${DOMAIN}`)
    - traefik.http.routers.photos_z720_net.entrypoints=websecure
    - traefik.http.routers.photos_z720_net.tls=true
    - traefik.http.routers.photos_z720_net.tls.certresolver=letsencrypt 
    - traefik.http.routers.photos_z720_net.middlewares=marker,redirectwww  
    expose:
      - 80/tcp
    hostname: ${DOMAIN}
    image: ghcr.io/z720/photos.z720.net:${VERSION:-develop}
    restart: unless-stopped
networks:
  default:
    external: true
    name: ${EXTERNAL_NETWORK:-engine_default}
